/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    residencies: Residency;
    services: Service;
    'coverage-areas': CoverageArea;
    testimonials: Testimonial;
    bookings: Booking;
    'process-steps': ProcessStep;
    'gallery-events': GalleryEvent;
    pages: Page;
    submissions: Submission;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    residencies: ResidenciesSelect<false> | ResidenciesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'coverage-areas': CoverageAreasSelect<false> | CoverageAreasSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'process-steps': ProcessStepsSelect<false> | ProcessStepsSelect<true>;
    'gallery-events': GalleryEventsSelect<false> | GalleryEventsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
    'home-hero': HomeHero;
    'about-page': AboutPage;
    'page-intros': PageIntro;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'page-intros': PageIntrosSelect<false> | PageIntrosSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Short description for screen readers.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residencies".
 */
export interface Residency {
  id: number;
  venue: string;
  /**
   * e.g. 'Resident DJ', 'Guest Slot', 'Headliner'
   */
  role: string;
  location?: string | null;
  status: 'current' | 'previous';
  /**
   * Lower numbers appear first within their group.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * e.g. "01", "02", ... "06"
   */
  number: string;
  title: string;
  /**
   * Short blurb shown on the service card.
   */
  description: string;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  /**
   * URL segment, e.g. wedding-dj-bournemouth. Generated from the title if left blank.
   */
  slug?: string | null;
  /**
   * Main page heading (H1), e.g. "Wedding DJ in Bournemouth & Dorset"
   */
  heroHeading?: string | null;
  /**
   * One or two sentences under the heading.
   */
  intro?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Question & answer pairs shown on the page and published as FAQ structured data. Write answers as direct, complete sentences.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Areas to highlight on this service page (defaults to all).
   */
  relatedAreas?: (number | CoverageArea)[] | null;
  /**
   * Optional overrides for Google and social previews. Leave blank to use the defaults generated from the page content.
   */
  seo?: {
    /**
     * Browser/search title. Aim for 50–60 characters.
     */
    metaTitle?: string | null;
    /**
     * Search snippet. Aim for 140–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Image shown when the page is shared on social (1200×630 ideal).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coverage-areas".
 */
export interface CoverageArea {
  id: number;
  name: string;
  /**
   * Short label on the card, e.g. "Hampshire"
   */
  detail?: string | null;
  order?: number | null;
  /**
   * URL segment, e.g. wedding-dj-bournemouth. Generated from the title if left blank.
   */
  slug?: string | null;
  /**
   * How this area is described to search engines.
   */
  schemaType?: ('City' | 'AdministrativeArea') | null;
  /**
   * Main page heading (H1), e.g. "Wedding & Event DJ in Poole"
   */
  heading?: string | null;
  intro?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Venues Adam has played or regularly works with in this area.
   */
  nearbyVenues?:
    | {
        name: string;
        type?: ('wedding' | 'club' | 'hotel' | 'festival' | 'other') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Question & answer pairs shown on the page and published as FAQ structured data. Write answers as direct, complete sentences.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional overrides for Google and social previews. Leave blank to use the defaults generated from the page content.
   */
  seo?: {
    /**
     * Browser/search title. Aim for 50–60 characters.
     */
    metaTitle?: string | null;
    /**
     * Search snippet. Aim for 140–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Image shown when the page is shared on social (1200×630 ideal).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  rating: number;
  authorName: string;
  /**
   * e.g. "Private Event — Ashdown Park"
   */
  eventType?: string | null;
  /**
   * 1–3 letters shown in the avatar circle
   */
  avatarInitials?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  date: string;
  eventName: string;
  venue?: string | null;
  type: 'festival' | 'residency' | 'wedding' | 'private' | 'corporate';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps".
 */
export interface ProcessStep {
  id: number;
  /**
   * "01" ... "04"
   */
  number: string;
  title: string;
  description: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-events".
 */
export interface GalleryEvent {
  id: number;
  label: string;
  /**
   * e.g. "Summer Residency", "Royal Regatta"
   */
  type: string;
  /**
   * Optional photo (replaces the animated bars).
   */
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment, e.g. wedding-dj-bournemouth. Generated from the title if left blank.
   */
  slug?: string | null;
  /**
   * Small uppercase label above the heading, e.g. "Pricing guide"
   */
  label?: string | null;
  /**
   * Main page heading (H1). Defaults to the title.
   */
  heroHeading?: string | null;
  intro?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Question & answer pairs shown on the page and published as FAQ structured data. Write answers as direct, complete sentences.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show the FAQ list above the body text (for pages where the FAQs are the main content).
   */
  showFaqsFirst?: boolean | null;
  /**
   * Optional overrides for Google and social previews. Leave blank to use the defaults generated from the page content.
   */
  seo?: {
    /**
     * Browser/search title. Aim for 50–60 characters.
     */
    metaTitle?: string | null;
    /**
     * Search snippet. Aim for 140–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Image shown when the page is shared on social (1200×630 ideal).
     */
    ogImage?: (number | null) | Media;
    /**
     * Hide this page from search engines and the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  name: string;
  email: string;
  eventType: 'wedding' | 'private' | 'corporate' | 'festival' | 'club' | 'residency' | 'other';
  eventDate?: string | null;
  venue?: string | null;
  message: string;
  submittedAt?: string | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'residencies';
        value: number | Residency;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'coverage-areas';
        value: number | CoverageArea;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'process-steps';
        value: number | ProcessStep;
      } | null)
    | ({
        relationTo: 'gallery-events';
        value: number | GalleryEvent;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residencies_select".
 */
export interface ResidenciesSelect<T extends boolean = true> {
  venue?: T;
  role?: T;
  location?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  description?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  order?: T;
  slug?: T;
  heroHeading?: T;
  intro?: T;
  body?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedAreas?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coverage-areas_select".
 */
export interface CoverageAreasSelect<T extends boolean = true> {
  name?: T;
  detail?: T;
  order?: T;
  slug?: T;
  schemaType?: T;
  heading?: T;
  intro?: T;
  body?: T;
  nearbyVenues?:
    | T
    | {
        name?: T;
        type?: T;
        url?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  rating?: T;
  authorName?: T;
  eventType?: T;
  avatarInitials?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  date?: T;
  eventName?: T;
  venue?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps_select".
 */
export interface ProcessStepsSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-events_select".
 */
export interface GalleryEventsSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  label?: T;
  heroHeading?: T;
  intro?: T;
  body?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  showFaqsFirst?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  eventType?: T;
  eventDate?: T;
  venue?: T;
  message?: T;
  submittedAt?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phone: string;
  email: string;
  mixcloudUrl: string;
  youtubeUrl?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'mixcloud' | 'youtube' | 'twitter' | 'tiktok' | 'other';
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Based in Bournemouth · Available South Coast & beyond"
   */
  locationTagline?: string | null;
  footerTagline?: string | null;
  /**
   * Exactly as it appears on Google Business Profile, e.g. "Adam Lewis Events"
   */
  businessName?: string | null;
  /**
   * Optional registered/trading name if different.
   */
  legalName?: string | null;
  /**
   * Google Maps share link for the business listing.
   */
  googleBusinessProfileUrl?: string | null;
  /**
   * Town, e.g. Bournemouth
   */
  addressLocality?: string | null;
  /**
   * County, e.g. Dorset
   */
  addressRegion?: string | null;
  /**
   * Optional — leave blank for a home-based business.
   */
  streetAddress?: string | null;
  /**
   * Optional outward code, e.g. BH1
   */
  postalCode?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Rough price band shown to search engines, e.g. "££"
   */
  priceRange?: string | null;
  /**
   * One per line in schema.org format, e.g. "Mo-Su 09:00-22:00"
   */
  openingHours?: string | null;
  /**
   * Default image for social previews (1200×630). Also used as the business image.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Google Analytics 4 measurement ID, e.g. "G-XXXXXXXXXX"
   */
  ga4MeasurementId?: string | null;
  /**
   * Google Search Console HTML-tag verification token (the content value only).
   */
  gscVerification?: string | null;
  /**
   * Bing Webmaster Tools msvalidate.01 token.
   */
  bingVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  /**
   * e.g. "Bournemouth, UK"
   */
  locationBadge?: string | null;
  /**
   * Small tagline above the title, e.g. "Former Hed Kandi Resident · 25+ Years"
   */
  heroLabel?: string | null;
  heroTitle: string;
  heroDescription: string;
  /**
   * Optional photo displayed in the hero (replaces the animated bars + AL badge).
   */
  heroImage?: (number | null) | Media;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Big initials/badge label, e.g. "AL"
   */
  badgeYears?: string | null;
  /**
   * e.g. "25+ Years Experience"
   */
  badgeLabel?: string | null;
  trustItems?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  marqueeItems?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * YouTube URL (e.g. https://youtu.be/abc123). Leave blank to hide the section.
   */
  videoUrl?: string | null;
  /**
   * Small label above the video, e.g. "Watch"
   */
  videoLabel?: string | null;
  /**
   * Heading above the video, e.g. "Hear the music"
   */
  videoHeading?: string | null;
  /**
   * Title of the video as it appears on YouTube (used for video search results).
   */
  videoTitle?: string | null;
  /**
   * One or two sentences describing the video (used for video search results).
   */
  videoDescription?: string | null;
  /**
   * Date the video was published on YouTube. Required for Google video results.
   */
  videoPublishedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  /**
   * Small uppercase section label, e.g. "About Adam"
   */
  label?: string | null;
  heading: string;
  paragraphs?:
    | {
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Name shown at bottom of narrative, e.g. "Adam Lewis"
   */
  byline?: string | null;
  /**
   * e.g. "DJ · 25+ years"
   */
  role?: string | null;
  stats?:
    | {
        value: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-intros".
 */
export interface PageIntro {
  id: number;
  residencies: {
    /**
     * Small uppercase section label above the heading.
     */
    label?: string | null;
    heading: string;
    subheading?: string | null;
  };
  services: {
    /**
     * Small uppercase section label above the heading.
     */
    label?: string | null;
    heading: string;
    subheading?: string | null;
  };
  availability: {
    /**
     * Small uppercase section label above the heading.
     */
    label?: string | null;
    heading: string;
    subheading?: string | null;
  };
  reviews: {
    /**
     * Small uppercase section label above the heading.
     */
    label?: string | null;
    heading: string;
    subheading?: string | null;
  };
  contact: {
    /**
     * Small uppercase section label above the heading.
     */
    label?: string | null;
    heading: string;
    subheading?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  mixcloudUrl?: T;
  youtubeUrl?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  locationTagline?: T;
  footerTagline?: T;
  businessName?: T;
  legalName?: T;
  googleBusinessProfileUrl?: T;
  addressLocality?: T;
  addressRegion?: T;
  streetAddress?: T;
  postalCode?: T;
  latitude?: T;
  longitude?: T;
  priceRange?: T;
  openingHours?: T;
  defaultOgImage?: T;
  ga4MeasurementId?: T;
  gscVerification?: T;
  bingVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  locationBadge?: T;
  heroLabel?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroImage?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  badgeYears?: T;
  badgeLabel?: T;
  trustItems?:
    | T
    | {
        label?: T;
        id?: T;
      };
  marqueeItems?:
    | T
    | {
        label?: T;
        id?: T;
      };
  videoUrl?: T;
  videoLabel?: T;
  videoHeading?: T;
  videoTitle?: T;
  videoDescription?: T;
  videoPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  paragraphs?:
    | T
    | {
        body?: T;
        id?: T;
      };
  byline?: T;
  role?: T;
  stats?:
    | T
    | {
        value?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-intros_select".
 */
export interface PageIntrosSelect<T extends boolean = true> {
  residencies?:
    | T
    | {
        label?: T;
        heading?: T;
        subheading?: T;
      };
  services?:
    | T
    | {
        label?: T;
        heading?: T;
        subheading?: T;
      };
  availability?:
    | T
    | {
        label?: T;
        heading?: T;
        subheading?: T;
      };
  reviews?:
    | T
    | {
        label?: T;
        heading?: T;
        subheading?: T;
      };
  contact?:
    | T
    | {
        label?: T;
        heading?: T;
        subheading?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}